# Generated by Django 4.0 on 2022-08-13 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ImageServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid1)),
                ('authorized_list', models.JSONField(default=list)),
            ],
        ),
    ]
